# Generated by Django 3.0.3 on 2020-03-16 10:06

import actionplan.models
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='actionplanmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100)),
                ('taskdesc', models.TextField(blank=True, null=True)),
                ('taskassignedby', models.CharField(max_length=100)),
                ('targetdate', models.DateField(default=datetime.date.today)),
                ('taskassigneddate', models.DateField(default=datetime.date.today)),
                ('taskassignswitch', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Deferred', 'Deferred'), ('In Progress', 'In Progress'), ('Waiting for Someone', 'Waiting for Someone')], max_length=50)),
                ('statusdesc', models.TextField(blank=True, null=True)),
                ('statuschangedate', models.DateField(default=datetime.date.today)),
                ('statuschangeswith', models.BooleanField(default=False)),
                ('completiondesc', models.TextField(blank=True, null=True)),
                ('completiondate', models.DateField(default=datetime.date.today)),
                ('completionuser', models.CharField(blank=True, max_length=100, null=True)),
                ('competeddatelog', models.DateField(default=datetime.date.today)),
                ('completionswitch', models.BooleanField(default=False)),
                ('verifiedcomments', models.TextField(blank=True, null=True)),
                ('verifieddate', models.DateField(default=datetime.date.today)),
                ('verifieddatelog', models.DateField(default=datetime.date.today)),
                ('verifiedswitch', models.BooleanField(default=False)),
                ('completionusername', models.ForeignKey(default='admin', on_delete=models.SET(actionplan.models.get_sentinel_user), related_name='completionusername', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Completed by')),
                ('statuschangeusername', models.ForeignKey(default='admin', on_delete=models.SET(actionplan.models.get_sentinel_user), related_name='statuschanger', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Status Changed by')),
                ('taskassignedto', models.ForeignKey(default='admin', on_delete=models.SET(actionplan.models.get_sentinel_user), related_name='actionassign_to_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Assign To')),
                ('taskassignusername', models.ForeignKey(default='admin', on_delete=models.SET(actionplan.models.get_sentinel_user), related_name='assign_by_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Assign To')),
                ('verifiedusername', models.ForeignKey(default='admin', on_delete=models.SET(actionplan.models.get_sentinel_user), related_name='verifiedusername', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Verified by')),
            ],
        ),
    ]
