# Generated by Django 3.0.3 on 2020-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionplan', '0002_auto_20200316_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionplanmodel',
            old_name='status_change_swith',
            new_name='status_change_switch',
        ),
    ]
