# Generated by Django 3.0.3 on 2020-03-17 07:20

import actionplan.models
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actionplan', '0004_auto_20200317_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplanmodel',
            name='datetime_creation',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='actionplanmodel',
            name='task_assign_username',
            field=models.ForeignKey(default='admin', on_delete=models.SET(actionplan.models.get_sentinel_user), related_name='assign_by_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Assign By   '),
        ),
    ]
