# Generated by Django 3.0.3 on 2020-03-17 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionplan', '0005_auto_20200317_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionplanmodel',
            name='competed_datelog',
        ),
        migrations.RemoveField(
            model_name='actionplanmodel',
            name='status_change_date',
        ),
        migrations.RemoveField(
            model_name='actionplanmodel',
            name='verified_datelog',
        ),
        migrations.AddField(
            model_name='actionplanmodel',
            name='completed_datetimelog',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='actionplanmodel',
            name='status_change_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='actionplanmodel',
            name='verified_datetimelog',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
