# Generated by Django 3.0.3 on 2020-03-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsmodel',
            name='validation_final_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imsmodel',
            name='validation_final_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imsmodel',
            name='transfer_comments_qa_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imsmodel',
            name='validation_qa_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
