# Generated by Django 3.0.3 on 2020-03-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20200309_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imsmodel',
            name='pt_doctor',
        ),
        migrations.AddField(
            model_name='imsmodel',
            name='pt_doctor1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
