# Generated by Django 3.0.3 on 2020-03-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_auto_20200309_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imsmodel',
            old_name='pt_doctor1',
            new_name='pt_doctor',
        ),
    ]
