# Generated by Django 3.0.3 on 2020-03-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20200309_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imsmodel',
            name='validation_final_reason',
            field=models.CharField(blank=True, default='Not Assigned', max_length=100, null=True),
        ),
    ]
