# Generated by Django 3.0.3 on 2020-03-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_auto_20200309_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imsmodel',
            name='validation_final_group',
        ),
        migrations.AddField(
            model_name='imsmodel',
            name='validation_final_grouptype',
            field=models.CharField(blank=True, default='Not Assigned', max_length=100, null=True),
        ),
    ]
