# Generated by Django 3.0.3 on 2020-03-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_auto_20200309_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imsmodel',
            old_name='validation_final_grouptype',
            new_name='validation_final_type',
        ),
    ]
