# Generated by Django 3.0.3 on 2020-03-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0010_auto_20200311_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imsmodel',
            old_name='qa_transfer_to',
            new_name='qa_assign_to',
        ),
    ]
