# Generated by Django 3.0.3 on 2020-03-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_auto_20200311_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imsmodel',
            old_name='transfer_qa_comments_confirm_switch',
            new_name='assign_qa_comments_confirm_switch',
        ),
        migrations.RenameField(
            model_name='imsmodel',
            old_name='transfer_qa_comments_update_timestamp',
            new_name='assign_qa_comments_update_timestamp',
        ),
        migrations.RenameField(
            model_name='imsmodel',
            old_name='transfer_qa_comments_user',
            new_name='assign_qa_comments_user',
        ),
    ]
