# Generated by Django 3.0.3 on 2020-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0013_auto_20200311_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsmodel',
            name='corrective_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
