# Generated by Django 3.0.3 on 2020-03-11 05:59

from django.conf import settings
from django.db import migrations, models
import ims.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ims', '0016_auto_20200311_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imsmodel',
            name='qa_assign_to',
            field=models.ForeignKey(default='admin', on_delete=models.SET(ims.models.get_sentinel_user), related_name='assign_to_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Assign To'),
        ),
    ]
