# Generated by Django 3.0.3 on 2020-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0018_auto_20200312_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignimages',
            name='assimage',
            field=models.FileField(blank=True, null=True, upload_to='assign_images'),
        ),
        migrations.AlterField(
            model_name='closureimages',
            name='cloimage',
            field=models.FileField(blank=True, null=True, upload_to='closure_images'),
        ),
        migrations.AlterField(
            model_name='investigationimages',
            name='invimage',
            field=models.FileField(blank=True, null=True, upload_to='investigation_images'),
        ),
        migrations.AlterField(
            model_name='submissionimages',
            name='subimage',
            field=models.FileField(blank=True, null=True, upload_to='submission_images'),
        ),
        migrations.AlterField(
            model_name='validationimages',
            name='valimage',
            field=models.FileField(blank=True, null=True, upload_to='validation_images'),
        ),
    ]
