# Generated by Django 3.0.3 on 2020-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0020_auto_20200312_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='imssubmissionfiles',
            name='subdate',
            field=models.DateTimeField(default=None),
        ),
    ]
