# Generated by Django 3.0.3 on 2020-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0021_imssubmissionfiles_subdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsassignfiles',
            name='assdate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='imsclosurefiles',
            name='clodate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='imsinvestigationfiles',
            name='invdate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='imsvalidationfiles',
            name='valdata',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
