# Generated by Django 3.0.3 on 2020-03-14 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0023_auto_20200313_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imsassignfiles',
            old_name='assdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='imsassignfiles',
            old_name='assfile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imsassignfiles',
            old_name='apost',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='imsclosurefiles',
            old_name='clodate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='imsclosurefiles',
            old_name='clofile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imsclosurefiles',
            old_name='cpost',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='imsinvestigationfiles',
            old_name='invdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='imsinvestigationfiles',
            old_name='invfile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imsinvestigationfiles',
            old_name='ipost',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='imssubmissionfiles',
            old_name='subdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='imssubmissionfiles',
            old_name='subfile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imssubmissionfiles',
            old_name='spost',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='imsvalidationfiles',
            old_name='valdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='imsvalidationfiles',
            old_name='valfile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imsvalidationfiles',
            old_name='vpost',
            new_name='post',
        ),
    ]
