# Generated by Django 3.0.3 on 2020-03-16 03:44

from django.conf import settings
from django.db import migrations, models
import ims.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ims', '0024_auto_20200314_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightsupdate', models.CharField(blank=True, max_length=100, null=True)),
                ('timstamp', models.DateTimeField(auto_now_add=True)),
                ('adminname', models.ForeignKey(default='admin', on_delete=models.SET(ims.models.get_sentinel_user), related_name='adminname', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Assign To')),
                ('username', models.ForeignKey(default='admin', on_delete=models.SET(ims.models.get_sentinel_user), related_name='access_given_to', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Assign To')),
            ],
        ),
    ]
