# Generated by Django 3.0.3 on 2020-03-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0026_auto_20200316_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imsadminlog',
            old_name='timstamp',
            new_name='timestamp',
        ),
    ]
