# Generated by Django 3.0.3 on 2020-02-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField(default=0)),
                ('dept_name', models.CharField(blank=True, default='Unknown', max_length=140, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_id', models.IntegerField(default=0)),
                ('loc_name', models.CharField(blank=True, default='Unknown', max_length=140, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(default=0)),
                ('emp_code', models.CharField(max_length=80)),
                ('doc_name', models.CharField(blank=True, default='Unknown', max_length=150, null=True, unique=True)),
                ('doc_sex', models.CharField(max_length=10)),
                ('doc_designation', models.CharField(max_length=150)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Departments', to_field='dept_name')),
            ],
        ),
    ]
