# Generated by Django 3.0.3 on 2020-03-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursequalitydata', '0002_auto_20200306_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intubation',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pressureinjury',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reintubation',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restraintinjury',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='returntoicu',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tracheostomy',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
    ]
