# Generated by Django 3.0.3 on 2020-02-25 15:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hicdata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.IntegerField()),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('pt_age', models.IntegerField()),
                ('dateofincident', models.DateField(default=datetime.date.today)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pt_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('pt_doctor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Doctors', to_field='doc_name')),
                ('pt_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VAE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.IntegerField()),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('pt_age', models.IntegerField()),
                ('dateofincident', models.DateField(default=datetime.date.today)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pt_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('pt_doctor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Doctors', to_field='doc_name')),
                ('pt_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thrombophlebitis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.IntegerField()),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('pt_age', models.IntegerField()),
                ('dateofincident', models.DateField(default=datetime.date.today)),
                ('Incidentdetails', models.TextField(blank=True, null=True)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pt_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('pt_doctor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Doctors', to_field='doc_name')),
                ('pt_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.IntegerField()),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('pt_age', models.IntegerField()),
                ('surgery_name', models.CharField(max_length=100)),
                ('surgery_date', models.DateTimeField(default=datetime.date.today)),
                ('dateofnotification', models.DateField(default=datetime.date.today)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pt_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('pt_doctor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Doctors', to_field='doc_name')),
                ('pt_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('surgery_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OT_list', to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NSI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('staff_age', models.IntegerField()),
                ('dateofincident', models.DateField(default=datetime.date.today)),
                ('Incidentdetails', models.TextField(blank=True, null=True)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CLABSI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.IntegerField()),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('pt_age', models.IntegerField()),
                ('dateofincident', models.DateField(default=datetime.date.today)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pt_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('pt_doctor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Doctors', to_field='doc_name')),
                ('pt_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CAUTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.IntegerField()),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('pt_age', models.IntegerField()),
                ('dateofincident', models.DateField(default=datetime.date.today)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pt_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('pt_doctor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Doctors', to_field='doc_name')),
                ('pt_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodyFluidExposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('staff_age', models.IntegerField()),
                ('staff_desig', models.CharField(max_length=100)),
                ('dateofincident', models.DateField(default=datetime.date.today)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('incident_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('staff_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Antibiotic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.IntegerField()),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('pt_age', models.IntegerField()),
                ('dateofadministration', models.DateField(default=datetime.date.today)),
                ('report_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pt_department', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Departments', to_field='dept_name')),
                ('pt_doctor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Doctors', to_field='doc_name')),
                ('pt_location', models.ForeignKey(blank=True, default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Locations', to_field='loc_name')),
                ('username', models.ForeignKey(default=6, on_delete=models.SET(hicdata.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
