# Generated by Django 3.0.3 on 2020-02-29 09:27

from django.db import migrations
import hicdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0002_cauti_device_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cauti',
            name='device_details',
        ),
        migrations.AddField(
            model_name='cauti',
            name='central_line',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
    ]
