# Generated by Django 3.0.3 on 2020-02-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0003_auto_20200229_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauti',
            name='central_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
