# Generated by Django 3.0.3 on 2020-02-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0011_cauti_centralline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cauti',
            name='centralline',
        ),
    ]
