# Generated by Django 3.0.3 on 2020-03-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0019_cauti_centralline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cauti',
            name='centralline',
        ),
    ]
