# Generated by Django 3.0.3 on 2020-03-01 05:45

from django.db import migrations
import hicdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0020_remove_cauti_centralline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauti',
            name='centralline',
            field=hicdata.models.DeviceDetailField(blank=True, null=True),
        ),
    ]
