# Generated by Django 3.0.3 on 2020-03-02 06:00

from django.db import migrations, models
import hicdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0023_cauti_centralline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauti',
            name='Root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='bloodinfection_organism',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='bloodinfection_sentivity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='comorbidities',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='criteria',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='patienttrack',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='patienttrack1',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='patienttrack2',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='patienttrack3',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='patienttrack4',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='patienttrack5',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='perpheralline',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='signssymptoms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='tracheostomy',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='urinarycatheter',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='urineculture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='urineculture_antibiotic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='urineculture_organism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='urineculture_pus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='urineculture_sensitivity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='urineculture_verify',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cauti',
            name='ventilated',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
    ]
