# Generated by Django 3.0.3 on 2020-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0024_auto_20200302_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauti',
            name='bloodinfection_report',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
