# Generated by Django 3.0.3 on 2020-03-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0025_cauti_bloodinfection_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cauti',
            old_name='Root_cause',
            new_name='root_cause',
        ),
    ]
