# Generated by Django 3.0.3 on 2020-03-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0027_auto_20200306_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibiotic',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cauti',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clabsi',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ssi',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='thrombophlebitis',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vae',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vap',
            name='pt_id',
            field=models.CharField(max_length=20),
        ),
    ]
