# Generated by Django 3.0.3 on 2020-03-06 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0028_auto_20200306_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibiotic',
            name='antibiotic_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='antibiotic_policy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='central_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='changes_made',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='cultures_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='cultures_taken',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='dateofadmission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='deescalation_antibiotic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='emperical_prescription',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='escalation_antibiotic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='pt_diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='pt_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
