# Generated by Django 3.0.3 on 2020-03-06 06:53

from django.db import migrations, models
import hicdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0029_auto_20200306_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clabsi',
            old_name='dateofincident',
            new_name='dateofrecognition',
        ),
        migrations.AddField(
            model_name='clabsi',
            name='centralline',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='comorbidities',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='criteria',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='culture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='culture_antibiotic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='culture_pus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='culture_sensitivity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='culture_verify',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='patienttrack',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='patienttrack1',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='patienttrack2',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='patienttrack3',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='patienttrack4',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='patienttrack5',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='perpheralline',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='secondary_organism',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='secondary_report',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='secondary_sentivity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='signssymptoms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='tracheostomy',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='urinarycatheter',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clabsi',
            name='ventilated',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
    ]
