# Generated by Django 3.0.3 on 2020-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0030_auto_20200306_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauti',
            name='comorbidities',
            field=models.CharField(blank=True, choices=[('DM', 'DM'), ('HTN', 'HTN'), ('CAD', 'CAD'), ('Renal Disease', 'Renal Disease'), ('Malignancy', 'Malignancy'), ('Asthma', 'Asthma'), ('Liver Disease', 'Liver Disease'), ('Immunosuppressed', 'Immunosuppressed'), ('Sepsis', 'Sepsis'), ('Malnourished', 'Malnourished'), ('Surgical Intervention', 'Surgical Invervention')], max_length=300, null=True),
        ),
    ]
