# Generated by Django 3.0.3 on 2020-03-06 09:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0032_auto_20200306_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauti',
            name='criteria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Appropriate Foley Catheterization', 'Appropriate Foley Catheterization'), ('Followed sterile technique', 'Followed sterile technique'), ('Urobag not touching floor', 'Urobag not touching floor'), ('urine flow not obstructed', 'urine flow not obstructed'), ('Meatal Care given', 'Meatal Care given'), ('Catheter Fixed to thigh', 'Catheter Fixed to thigh'), ('Hand Hygiene before and after catheter handling', 'Hand Hygiene before and after catheter handling'), ('Reviewed need of catheter removal', 'Reviewed need of catheter removal'), ('Breaks in closed system', 'Breaks in closed system'), ('Staffing level', 'Staffing level'), ('Urine sent for routine examination', 'Urine sent for routine examination')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cauti',
            name='signssymptoms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fever', 'Fever'), ('Urgency', 'Urgency'), ('Frequency', 'Frequency'), ('Dysuria', 'Dysuria'), ('Suprapubic tenderness', 'Suprapubic tenderness'), ('Abcess', 'Abcess'), ('Apnoea', 'Apnoea'), ('Bradycardia', 'Bradycardia'), ('Costovertebral ankle pain', 'Costobertebral ankle pain'), ('Purulent drainage', 'Purulant drainage'), ('Hypotherma', 'Hypothermia'), ('Vomiting', 'Vomiting'), ('Lethargy', 'Lethargy')], max_length=300, null=True),
        ),
    ]
