# Generated by Django 3.0.3 on 2020-03-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0035_auto_20200306_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vap',
            name='dateofadmission',
        ),
        migrations.RemoveField(
            model_name='vap',
            name='dateofdischarge',
        ),
    ]
