# Generated by Django 3.0.3 on 2020-03-06 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0036_auto_20200306_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='vap',
            name='dateofadmission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vap',
            name='dateofdischarge',
            field=models.DateField(blank=True, null=True),
        ),
    ]
