# Generated by Django 3.0.3 on 2020-03-07 04:33

from django.db import migrations, models
import hicdata.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hicdata', '0037_auto_20200306_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vae',
            old_name='dateofincident',
            new_name='dateofrecognition',
        ),
        migrations.AddField(
            model_name='vap',
            name='centralline',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='comorbidities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DM', 'DM'), ('HTN', 'HTN'), ('CAD', 'CAD'), ('Renal Disease', 'Renal Disease'), ('Malignancy', 'Malignancy'), ('Asthma', 'Asthma'), ('Liver Disease', 'Liver Disease'), ('Immunosuppressed', 'Immunosuppressed'), ('Sepsis', 'Sepsis'), ('Malnourished', 'Malnourished'), ('Surgical Intervention', 'Surgical Invervention'), ('Obesity', 'Obesity'), ('Lung Disease', 'Lung Disease')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='criteria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Appropriate indication for intubation and mechanical ventilation', 'Appropriate indication for intubation and mechanical ventilation'), ('Followed sterile technique', 'Followed sterile technique'), ('Hand Hygiene before and after handling', 'Hand Hygiene before and after handling'), ('Head elavation greater than 30 degrees', 'Head elavation greater than 30 degrees'), ('Daily sedationo vacation', 'Daily sedation vacation'), ('Ventilation tube changed due to any malfunctioning?', 'Ventilation tube changed due to any malfunctioning?'), ('Ventilation tube changed due to due to soiled with secretion?', 'Ventilation tube changed due to soiled with secretion?'), ('Humidifier change within 24-48 hourss', 'Humidifier change within 24-48 hourss'), ('Peptic ulcer disease prophyaxis', 'Peptic ulcer disease prophyaxis'), ('DVT prophylaxis', 'DVT Prophylaxis'), ('Adequate and regular suctioning', 'Adequate and regualr suctioning'), ('Chest physiotherapy', 'Chest physiotherapy'), ('Cuff pressure monitoring 22-24 cm H2O', 'Cuff pressure monitoring 22-24 cm H2O'), ('Cuff pressure monitoring less than 22cm H2O', 'Cuff pressure monitoring < 22 cm H2O'), ('VAP case definition fulfilled', 'VAP case definition fullfilled'), ('Attempt made at waning the pateint out of ventilator', 'Attempt made at weaning patient out of ventilator'), ('Adequete Staffing level', 'Adequete staffing level'), ('Culture sent?', 'Culture sent?'), ('Any suspencted secondary blood stream infection?', 'Any suspencted secondary blood stream infection?')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='culture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='culture_antibiotic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='culture_organism',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='culture_sensitivity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='culture_verify',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='patienttrack',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='patienttrack1',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='patienttrack2',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='patienttrack3',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='patienttrack4',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='patienttrack5',
            field=hicdata.models.PatientTrackerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='perpheralline',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='secondary_organism',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='secondary_report',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='secondary_sentivity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='signssymptoms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fever', 'Fever'), ('Leukocytosis', 'Leukocytosis'), ('Positive culture report', 'Positive culture report'), ('Apnoea', 'Apnoea'), ('Bradycardia', 'Bradycardia')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='tracheostomy',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='urinarycatheter',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='ventilated',
            field=hicdata.models.DeviceDetailsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vap',
            name='xrayfindings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clabsi',
            name='criteria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Appropriate indication for central line insertion', 'Appropriate indication for central line insertion'), ('Followed sterile technique', 'Followed sterile technique'), ('Hand Hygiene before and after handling', 'Hand Hygiene before and after handling'), ('PPE, Sterile gloves, steril gown, Mask used during insertion', 'PPE, Sterile gloves, steril gown, Mask used during insertion'), ('Proper site cleaning (with 70% Isopropyl alcohol or 2% Cholorohexidine', 'Proper site cleaning (with 70% Isopropyl alcohol or 2% Cholorohexidine'), ('Anticeptic Dressing used', 'Anticeptic Dressing used'), ('Hub cleaning after use', 'Hub cleaning after use'), ('unused injection port kept closed?', 'unused injection port kept closed?'), ('Aseptic technique followed before each use?', 'Aseptic technique followed before each use?'), ('Review of insertion site done daily', 'Review of insertion done daily'), ('Staffing level', 'Staffing level'), ('Antibiotic prescribed as per culture report', 'Antibiotic prescribed as per culture report'), ('Antibiotic prescribed as per antibiotic policy', 'Antibiotic prescribed as per antibiotic policy')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clabsi',
            name='culture',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Not Sent', 'Not Sent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clabsi',
            name='signssymptoms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fever', 'Fever'), ('Leukocytosis', 'Leukocytosis'), ('Abcess', 'Abcess'), ('Apnoea', 'Apnoea'), ('Bradycardia', 'Bradycardia'), ('Pain', 'Pain'), ('Tenderness', 'Tenderness'), ('Purulent drainage', 'Purulant drainage'), ('Hypotherma', 'Hypothermia'), ('Vomiting', 'Vomiting'), ('Lethargy', 'Lethargy')], max_length=300, null=True),
        ),
    ]
